name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configure AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Authenticate to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

		# Create .env file
    - name: Create .env file
      run: |
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" > .env
        echo "SESSION_EXPIRES_SEC=${{ secrets.SESSION_EXPIRES_SEC }}" >> .env
        echo "BCRYPT_SALT_ROUNDS=${{ secrets.BCRYPT_SALT_ROUNDS }}" >> .env
        echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> .env
        echo "HOST_PORT=${{ secrets.HOST_PORT }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "CDN_URL=${{ secrets.CDN_URL }}" >> .env
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
        echo "S3_BUCKET_REGION=${{ secrets.S3_BUCKET_REGION }}" >> .env
        echo "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> .env
        echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
        cat .env

    # Build Docker image and Tag and Push Docker Image to ECR
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # Generate Dockerrun.aws.json
    - name: Generate Dockerrun.aws.json
      run: |
        sed "s|<ECR_REGISTRY>/<ECR_REPOSITORY>:<IMAGE_TAG>|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" Dockerrun.template.json > Dockerrun.aws.json

    # Create deployment package
    - name: Create Deployment Package
      run: zip -r deploy.zip . -x '*.git*'

    # Deploy to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: backend
        environment_name: backend-env
        version_label: v-${{ github.run_id }}-$(date +'%Y%m%d%H%M%S')
        use_existing_version_if_available: true
        region: ap-northeast-2
        deployment_package: deploy.zip
